services:
  - type: web
    name: suba-backend
    env: docker
    envVars:
      - key: APP_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: APP_SECRET_KEY
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: SUPABASE_JWT_SECRET
        sync: false
